const DEBOT_PREFIX = 'DEBOT_';
const CLIENT_PREFIX = 'CLIENT_';

export const EVENTS = {
	DEBOT: {
		FUNCTION_CALLED: `${DEBOT_PREFIX}FUNCTION_CALLED`,
		FUNCTION_EXECUTED: `${DEBOT_PREFIX}FUNCTION_EXECUTED`,
		FUNCTION_EXECUTION_FAILED: `${DEBOT_PREFIX}FUNCTION_EXECUTION_FAILED`,
	},
	CLIENT: {
		EXECUTE_FUNCTION: `${CLIENT_PREFIX}EXECUTE_FUNCTION`,
	},
}
