export const USER_DEBOTS_LS_FIELD = 'USER_DEBOTS_LS_FIELD';
export const USER_ENV_LS_FIELD = 'USER_ENV_LS_FIELD';
export const TON_NETWORK_LS_FIELD = 'TON_NETWORK_LS_FIELD';
export const WALLET_LS_FIELD = 'WALLET_LS_FIELD';
